language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t omesadev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true omesadev/docker-react npm run test